from django.shortcuts import render
from django.http import HttpResponseBadRequest, JsonResponse
from .imageup import upload_image_to_drive
import os
from django.conf import settings
# Create your views here.
def Base(request):
  # Your custom logic goes here
  data = "This is data generated by the custom function."
  return render(request, 'Base.html', {'data': data})
def upload_images(request):
  """
  Handles image upload requests.

  Expects a POST request with a 'files' key in the request.FILES dictionary
  containing the selected images.

  Returns:
      A JSON response with information about uploaded images or an error message.
  """
  if request.method != 'POST':
    return HttpResponseBadRequest('Only POST requests are allowed')

  # Get the folder ID from request data or settings (replace with your logic)
  folder_id = 'YOUR_FOLDER_ID'

  uploaded_files = []
  for image in request.FILES.getlist('files'):
    file_path = os.path.join(settings.MEDIA_ROOT, image.name)
    with open(file_path, 'wb+') as destination:
      for chunk in image.chunks():
        destination.write(chunk)
    uploaded_file = upload_image_to_drive(file_path, folder_id)
    if uploaded_file:
      uploaded_files.append({'name': uploaded_file['name'], 'id': uploaded_file['id']})
    else:
      return JsonResponse({'error': 'Failed to upload an image'}, status=500)
    os.remove(file_path)  # Remove temporary file

  return JsonResponse({'uploaded_files': uploaded_files})